version: '3.2'
services:
  pajbot_web:
    build:
      context: .
      dockerfile: PajbotDockerfile
    env_file:
      - .env
    ports:
      - "7070:2325" # Forward container port 2325 to host port 7070
    volumes:
      - /opt/pajbots/:/opt/www/configs # /opt/pajbots/ is the host folder, /opt/www/configs is the folder in the container
    depends_on:
      - mysql
      - redis
      - kraken
    command: ["python3", "app.py", "--config", "configs/config.ini"]

  pajbot_bot:
    build:
      context: .
      dockerfile: PajbotDockerfile
    restart: unless-stopped # Enabled auto restart, since the bot is gonna crash until redis has token
    env_file:
      - .env
    volumes:
      - /opt/pajbots/:/opt/www/configs # /opt/pajbots/ is the host folder, /opt/www/configs is the folder in the container
    depends_on:
      - mysql
      - redis
      - kraken
    command: ["python3", "main.py", "--config", "configs/config.ini"]

  kraken:
    image: zwb3/twitch-api-v3-proxy:latest
    restart: always
    command: ["/opt/twitch-api-v3-proxy-boot/bin/twitch-api-v3-proxy", "--server.address=0.0.0.0", "--clientId=${CLIENTID}"] # CLIENTID is enviroment variable on server

  redis:
    image: redis:latest
    restart: always
    volumes:
      - pajbot-redis:/data
    command: ["redis-server", "--appendonly", "yes"]

  mysql:
    build:
      context: .
      dockerfile: MariaDBDockerfile
    restart: always
    volumes:
      - pajbot-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=myroot
      - MYSQL_USER=user1;user2
      - MYSQL_PASSWORD=pass1;pass2
      - MYSQL_DATABASE=db1;db2

volumes:
  pajbot-db:
    driver: local
  pajbot-redis:
    driver: local